"""added password column

Revision ID: d2b6d2166c95
Revises: 902cc3a815fe
Create Date: 2023-06-27 16:42:36.008706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b6d2166c95'
down_revision = '902cc3a815fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.drop_column('passowrd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passowrd', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
